import { BoilerBrand, ConnectionType, Product } from './types';

// Helper to categorize boiler list
const PRIORITY_BRANDS = [
  'Baxi', 'Bosch', 'Buderus', 'Ferroli', 'Navien', 'Protherm', 'Vaillant', 'Viessmann', 'Zota', 'Эван'
];

const RAW_BRANDS: BoilerBrand[] = [
  { name: 'Котел с OpenTherm', models: [{ name: 'Котел с OpenTherm', connectionType: ConnectionType.OPENTHERM }] },
  { name: 'Котел с eBus', models: [{ name: 'Котел с eBus', connectionType: ConnectionType.EBUS }] },
  { name: 'Котел с BSB', models: [{ name: 'Котел с BSB', connectionType: ConnectionType.BSB }] },
  { name: 'Котел с входом термостата', models: [{ name: 'Котел с входом термостата', connectionType: ConnectionType.RELAY }] },
  { name: 'Котел с входом 0-10В', models: [{ name: 'Котел с входом 0-10В', connectionType: ConnectionType.V0_10 }] },
  { name: 'ACV', models: [
      { name: 'Alfa Sprint', connectionType: ConnectionType.RELAY },
      { name: 'Alfa Comfort E', connectionType: ConnectionType.RELAY },
      { name: 'BIOmax', connectionType: ConnectionType.RELAY },
      { name: 'Compact A', connectionType: ConnectionType.RELAY },
      { name: 'Delta Performance', connectionType: ConnectionType.RELAY },
      { name: 'Delta Pro', connectionType: ConnectionType.RELAY },
      { name: 'E-Tech', connectionType: ConnectionType.RELAY },
      { name: 'ETS 9-24', connectionType: ConnectionType.RELAY },
      { name: 'Heat Master N', connectionType: ConnectionType.RELAY },
      { name: 'HR Solo', connectionType: ConnectionType.OPENTHERM },
      { name: 'HRE eco', connectionType: ConnectionType.OPENTHERM },
      { name: 'Kompakt HRE eco', connectionType: ConnectionType.OPENTHERM },
      { name: 'N1', connectionType: ConnectionType.RELAY },
      { name: 'N2', connectionType: ConnectionType.RELAY },
      { name: 'N3', connectionType: ConnectionType.RELAY },
      { name: 'N-Mini', connectionType: ConnectionType.RELAY },
      { name: 'Prestige 42-120 Solo', connectionType: ConnectionType.RELAY },
      { name: 'Prestige Excellence 18 - 32 Mklll', connectionType: ConnectionType.RELAY },
      { name: 'TKAN 1', connectionType: ConnectionType.RELAY },
      { name: 'TKAN 2', connectionType: ConnectionType.RELAY },
    ] 
  },
  { name: 'AEG', models: [
      { name: 'GBA', connectionType: ConnectionType.RELAY },
      { name: 'GBT', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Alpenhoff', models: [{ name: 'Gamburg', connectionType: ConnectionType.RELAY }]},
  { name: 'AlphaTherm', models: [
      { name: 'Alpha M', connectionType: ConnectionType.RELAY },
      { name: 'Beta ATE', connectionType: ConnectionType.RELAY },
      { name: 'Delta AT', connectionType: ConnectionType.RELAY },
      { name: 'Delta ATB', connectionType: ConnectionType.RELAY },
      { name: 'Delta AG', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Amber', models: [{ name: 'DHEL 412', connectionType: ConnectionType.RELAY }]},
  { name: 'Arderia', models: [
      { name: 'E4 - E24', connectionType: ConnectionType.ARDERIA },
      { name: 'E4 - E24 (с 09.2025г.)', connectionType: ConnectionType.OPENTHERM },
      { name: 'E20m', connectionType: ConnectionType.ARDERIA },
      { name: 'D10 - D40', connectionType: ConnectionType.ARDERIA },
      { name: 'D10 - D40 Atmo', connectionType: ConnectionType.ARDERIA },
      { name: 'B10 - B24', connectionType: ConnectionType.ARDERIA },
      { name: 'SB24 - SB40', connectionType: ConnectionType.ARDERIA },
      { name: 'S10 - S40', connectionType: ConnectionType.ARDERIA },
  ]},
  { name: 'Arideya', models: [{ name: 'Arideya Grand', connectionType: ConnectionType.RELAY }]},
  { name: 'Ariston', models: [
      { name: 'CARES X - HS X', connectionType: ConnectionType.EBUS },
      { name: 'CLASS X - XC', connectionType: ConnectionType.EBUS },
      { name: 'Genus One System', connectionType: ConnectionType.EBUS },
      { name: 'Genus EVO', connectionType: ConnectionType.EBUS },
      { name: 'Genus Premium EVO', connectionType: ConnectionType.EBUS },
      { name: 'ALIXIA S / ULTRA', connectionType: ConnectionType.RELAY },
      { name: 'Alteas X / ONE NET', connectionType: ConnectionType.RELAY },
      { name: 'BS II FF / CF', connectionType: ConnectionType.RELAY },
      { name: 'EGIS PLUS FF / CF', connectionType: ConnectionType.RELAY },
      { name: 'EGIS BS FF / CF', connectionType: ConnectionType.RELAY },
      { name: 'Unobloc G PV 24-31 RI G 38-45 RI', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Attack', models: [
      { name: 'EKO', connectionType: ConnectionType.RELAY },
      { name: 'PLQ', connectionType: ConnectionType.RELAY },
      { name: 'KLQ', connectionType: ConnectionType.RELAY },
      { name: 'KLV', connectionType: ConnectionType.RELAY },
      { name: 'EZ', connectionType: ConnectionType.RELAY },
      { name: 'E', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'BaltGAZ', models: [
      { name: 'Turbo S (с платой BRAHMA 1966)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Nevatec 24 Turbo, Turbo E 24, Turbo', connectionType: ConnectionType.RELAY },
      { name: 'Turbo E', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Baltur', models: [
      { name: 'Tesis', connectionType: ConnectionType.OPENTHERM },
      { name: 'BTG', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Baxi', models: [
      { name: 'Luna 3', connectionType: ConnectionType.OPENTHERM },
      { name: 'Luna 3 Comfort', connectionType: ConnectionType.OPENTHERM },
      { name: 'ECO Life', connectionType: ConnectionType.OPENTHERM },
      { name: 'ECO Nova', connectionType: ConnectionType.OPENTHERM },
      { name: 'Eco 4S', connectionType: ConnectionType.OPENTHERM },
      { name: 'Eco Four', connectionType: ConnectionType.OPENTHERM },
      { name: 'MainFour', connectionType: ConnectionType.OPENTHERM },
      { name: 'Eco Home', connectionType: ConnectionType.OPENTHERM },
      { name: 'Fourtech', connectionType: ConnectionType.OPENTHERM },
      { name: 'ECO Classic', connectionType: ConnectionType.OPENTHERM },
      { name: 'Slim-in (до 2023)', connectionType: ConnectionType.RELAY },
      { name: 'Slim-in (с 2023)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Slim HPS', connectionType: ConnectionType.RELAY },
      { name: 'Ampera', connectionType: ConnectionType.OPENTHERM },
      { name: 'Ampera Plus', connectionType: ConnectionType.OPENTHERM },
      { name: 'Ampera Pro', connectionType: ConnectionType.OPENTHERM },
      { name: 'Nuvola 3', connectionType: ConnectionType.OPENTHERM },
      { name: 'Nuvola 3 Comfort', connectionType: ConnectionType.OPENTHERM },
      { name: 'Luna Duo-tec MP+', connectionType: ConnectionType.BSB },
      { name: 'Luna Duo-tec MP', connectionType: ConnectionType.BSB },
      { name: 'Luna Platinum+', connectionType: ConnectionType.BSB },
      { name: 'Power HT+', connectionType: ConnectionType.BSB },
      { name: 'Power HT-A', connectionType: ConnectionType.BSB },
      { name: 'Nuvola Duo-Tec', connectionType: ConnectionType.OPENTHERM },
      { name: 'Nuvola Duo-Tec+', connectionType: ConnectionType.OPENTHERM },
      { name: 'ECO-5 Compact', connectionType: ConnectionType.OPENTHERM },
      { name: 'Main 5', connectionType: ConnectionType.OPENTHERM },
      { name: 'Luna Duo-Tec', connectionType: ConnectionType.OPENTHERM },
      { name: 'Duo-Tec E', connectionType: ConnectionType.OPENTHERM },
      { name: 'Duo-Tec Air', connectionType: ConnectionType.OPENTHERM },
      { name: 'Duo-Tec Compact', connectionType: ConnectionType.OPENTHERM },
    ] 
  },
  { name: 'Bentone', models: [{ name: 'Горелка ST120KA', connectionType: ConnectionType.RELAY }]},
  { name: 'Beretta', models: [
      { name: 'CIAO C.S.I', connectionType: ConnectionType.OPENTHERM },
      { name: 'Avtonom / RAG', connectionType: ConnectionType.RELAY },
      { name: 'CITY 24-28 RSI-CSI', connectionType: ConnectionType.RELAY },
      { name: 'Fabula', connectionType: ConnectionType.RELAY },
      { name: 'Mynute DGT', connectionType: ConnectionType.RELAY },
      { name: 'RAI / RAI PV', connectionType: ConnectionType.RELAY },
      { name: 'Novella', connectionType: ConnectionType.RELAY },
      { name: 'Maxima', connectionType: ConnectionType.RELAY },
      { name: 'Verona', connectionType: ConnectionType.RELAY },
      { name: 'Excluzive', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Biasi', models: [
      { name: 'Binova', connectionType: ConnectionType.RELAY },
      { name: 'Kappa', connectionType: ConnectionType.RELAY },
      { name: 'Super kappa', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Biodom', models: [
      { name: '27C5', connectionType: ConnectionType.RELAY },
      { name: 'C15', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'BIOTEP', models: [{ name: '8 - 32 кВт', connectionType: ConnectionType.RELAY }]},
  { name: 'Bosch', models: [
      { name: 'GAZ 2500F', connectionType: ConnectionType.OPENTHERM },
      { name: 'GAS 6000W', connectionType: ConnectionType.OPENTHERM },
      { name: 'GAZ 2000F', connectionType: ConnectionType.RELAY },
      { name: 'GAZ 3000W', connectionType: ConnectionType.RELAY },
      { name: 'GAZ 4000W (ZWA)', connectionType: ConnectionType.RELAY },
      { name: 'GAZ 7000W (ZSC / ZWC)', connectionType: ConnectionType.RELAY },
      { name: 'Supraline', connectionType: ConnectionType.RELAY },
      { name: 'Tronic Heat', connectionType: ConnectionType.RELAY },
      { name: 'Condens 2500W', connectionType: ConnectionType.RELAY },
      { name: 'Condens 7000IW', connectionType: ConnectionType.RELAY },
    ]
  },
  { name: 'Brotje', models: [{ name: 'WCL WLS 24-28', connectionType: ConnectionType.RELAY }]},
  { name: 'Buderus', models: [
      { name: 'Logamax U072', connectionType: ConnectionType.OPENTHERM },
      { name: 'Logamatic 2101 / 2107 / 2109', connectionType: ConnectionType.RELAY },
      { name: 'Logamatic 4211 / 4321 / 4322', connectionType: ConnectionType.RELAY },
      { name: 'Logamatic 5311 / 5313', connectionType: ConnectionType.RELAY },
      { name: 'Logamatic MC110', connectionType: ConnectionType.RELAY },
      { name: 'Logamax E213', connectionType: ConnectionType.RELAY },
      { name: 'Logamax GB072', connectionType: ConnectionType.RELAY },
      { name: 'Logamax U024', connectionType: ConnectionType.RELAY },
      { name: 'Logamax U032 / U034', connectionType: ConnectionType.RELAY },
      { name: 'Logamax U042 / U044', connectionType: ConnectionType.RELAY },
      { name: 'Logamax U052 / U054', connectionType: ConnectionType.RELAY },
      { name: 'Logamax U068', connectionType: ConnectionType.RELAY },
      { name: 'Logamax plus GB062', connectionType: ConnectionType.EMS_PLUS },
      { name: 'Logamax plus GB162', connectionType: ConnectionType.EMS_PLUS },
      { name: 'Logamax plus GB122i', connectionType: ConnectionType.EMS_PLUS },      
      { name: 'Logamax plus GB172I', connectionType: ConnectionType.EMS_PLUS },
      { name: 'Logamax plus GB272', connectionType: ConnectionType.EMS_PLUS },
      { name: 'Logano G124 WS', connectionType: ConnectionType.RELAY },
    ]
  },
  { name: 'Chaffoteaux', models: [
      { name: 'Alixia FF/CF', connectionType: ConnectionType.RELAY },
      { name: 'Niagara C FF/CF', connectionType: ConnectionType.RELAY },
      { name: 'Pigma FF/CF', connectionType: ConnectionType.RELAY },
      { name: 'Talia FF/CF', connectionType: ConnectionType.RELAY },
      { name: 'Talia System', connectionType: ConnectionType.RELAY },
      { name: 'Mira CF / MX2 CF', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Chaffoteaux&Maury', models: [
      { name: 'Mira Comfort CF', connectionType: ConnectionType.RELAY },
      { name: 'System Plus FF', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Copa', models: [
      { name: 'EOMIX', connectionType: ConnectionType.RELAY },
      { name: 'EON', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'CTC', models: [
      { name: 'BETA 950/960', connectionType: ConnectionType.RELAY },
      { name: '1200 Family', connectionType: ConnectionType.RELAY },
      { name: 'Silver / Silver BL', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Cuenod', models: [{ name: 'NC4 / NC9', connectionType: ConnectionType.RELAY }]},
  { name: 'Dakon', models: [
      { name: 'GL ECO', connectionType: ConnectionType.RELAY },
      { name: 'NM', connectionType: ConnectionType.RELAY },
      { name: 'P LUX Z', connectionType: ConnectionType.RELAY },
      { name: 'PTE / PTE-M', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Danvex', models: [{ name: 'B (30-220)', connectionType: ConnectionType.RELAY }]},
  { name: 'De Dietrich', models: [
      { name: 'AMC (Diematic Evolution)', connectionType: ConnectionType.OPENTHERM },
      { name: 'NANEO PMC-S MI', connectionType: ConnectionType.OPENTHERM },
      { name: 'Vivadens MCR', connectionType: ConnectionType.OPENTHERM },
      { name: 'ZENA MS', connectionType: ConnectionType.OPENTHERM },
      { name: 'ZENA PLUS MSL', connectionType: ConnectionType.OPENTHERM },
      { name: 'С 330 / С630 (с блоком iniControl)', connectionType: ConnectionType.OPENTHERM },
      { name: 'DTG S', connectionType: ConnectionType.RELAY },
      { name: 'DTG X', connectionType: ConnectionType.RELAY },
      { name: 'PMC', connectionType: ConnectionType.RELAY },
      { name: 'Diematic 3', connectionType: ConnectionType.RELAY },
      { name: 'Diematic M3', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Domusa', models: [{ name: 'Ecogas 60-100', connectionType: ConnectionType.RELAY }]},
  { name: 'Dozatech', models: [{ name: 'Контроллер RK-2006LP', connectionType: ConnectionType.RELAY }]},
  { name: 'Dragon', models: [{ name: 'Горелка ТЕРМИНАТОР- 15', connectionType: ConnectionType.RELAY }]},
  { name: 'ECA', models: [
      { name: 'Arceus', connectionType: ConnectionType.RELAY },
      { name: 'Proteus Premix', connectionType: ConnectionType.RELAY },
      { name: 'Confeo Premix', connectionType: ConnectionType.RELAY },
      { name: 'Gelios Plus', connectionType: ConnectionType.RELAY },
      { name: 'Gerda', connectionType: ConnectionType.RELAY },
      { name: 'Arceus (c 2024)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Proteus Premix (c 2024)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Confeo Premix (c 2024)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Gelios Plus (c 2024)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Gerda (c 2024)', connectionType: ConnectionType.OPENTHERM },
  ]},
  { name: 'Elco', models: [
      { name: 'Thirison L Plus', connectionType: ConnectionType.EBUS },
      { name: 'Горелка VG 40-85', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Electrolux', models: [
      { name: 'FSB', connectionType: ConnectionType.RELAY },
      { name: 'GB Basic Space S FI', connectionType: ConnectionType.RELAY },
      { name: 'GBC Hi Tech', connectionType: ConnectionType.RELAY },
      { name: 'Basic X / Basic Space', connectionType: ConnectionType.RELAY },
      { name: 'Quantum', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Evberg', models: [{ name: 'LUX / W', connectionType: ConnectionType.RELAY }]},
  { name: 'Faci', models: [{ name: 'SY 400', connectionType: ConnectionType.RELAY }]},
  { name: 'Federica Bugatti', models: [
      { name: 'Varme', connectionType: ConnectionType.OPENTHERM },
      { name: 'Infinito ION Plus', connectionType: ConnectionType.OPENTHERM },
      { name: 'Tech', connectionType: ConnectionType.OPENTHERM },
      { name: 'Turbo Plus', connectionType: ConnectionType.RELAY },
      { name: 'ECO', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'FER', models: [{ name: 'Seven D LN', connectionType: ConnectionType.OPENTHERM }]},
  { name: 'Ferroli', models: [
      { name: 'Seven D LN', connectionType: ConnectionType.OPENTHERM },
      { name: 'Arena C, F', connectionType: ConnectionType.OPENTHERM },
      { name: 'Atlas EVO', connectionType: ConnectionType.OPENTHERM },
      { name: 'Bluehelix Tech S', connectionType: ConnectionType.OPENTHERM },
      { name: 'Diva F', connectionType: ConnectionType.OPENTHERM },
      { name: 'Divatech D, F', connectionType: ConnectionType.OPENTHERM },
      { name: 'Divatop', connectionType: ConnectionType.OPENTHERM },
      { name: 'Domicompact C', connectionType: ConnectionType.OPENTHERM },
      { name: 'Domiproject C, F', connectionType: ConnectionType.OPENTHERM },
      { name: 'Econcept TECH', connectionType: ConnectionType.OPENTHERM },
      { name: 'Fortuna C, F', connectionType: ConnectionType.OPENTHERM },
      { name: 'New elite C, F', connectionType: ConnectionType.OPENTHERM },
      { name: 'Pegasus D', connectionType: ConnectionType.OPENTHERM },
      { name: 'Vitabel HF, C, F', connectionType: ConnectionType.OPENTHERM },
      { name: 'Atlas, D', connectionType: ConnectionType.RELAY },
      { name: 'Tor', connectionType: ConnectionType.OPENTHERM },
      { name: 'Tantaqua N EL', connectionType: ConnectionType.RELAY },
      { name: 'Domina', connectionType: ConnectionType.RELAY },
      { name: 'Fortuna PRO / SPECIAL', connectionType: ConnectionType.RELAY },
      { name: 'GN1 K, N', connectionType: ConnectionType.RELAY },
      { name: 'LEB', connectionType: ConnectionType.RELAY },
      { name: 'Pegasus', connectionType: ConnectionType.RELAY },
      { name: 'Prextherm RSW', connectionType: ConnectionType.RELAY },
      { name: 'Rendimax N EL', connectionType: ConnectionType.RELAY },
      { name: 'ZEWS', connectionType: ConnectionType.RELAY },
    ]
  },
  { name: 'Fil', models: [{ name: 'SPL', connectionType: ConnectionType.RELAY }]},
  { name: 'Fondital', models: [
      { name: 'Antea', connectionType: ConnectionType.OPENTHERM },
      { name: 'Formentera', connectionType: ConnectionType.OPENTHERM },
      { name: 'Elba Dual', connectionType: ConnectionType.RELAY },
      { name: 'Minorca', connectionType: ConnectionType.RELAY },
      { name: 'Victoria Compact CTFS 24 AF', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Foreman', models: [{ name: 'WH Foremann MF300', connectionType: ConnectionType.RELAY }]},
  { name: 'Fumis', models: [{ name: 'Fumis Alpha', connectionType: ConnectionType.RELAY }]},
  { name: 'Fuzzy', models: [{ name: 'Logic 310LG RTC', connectionType: ConnectionType.RELAY }]},
  { name: 'Galan', models: [{ name: 'Navigator STELS', connectionType: ConnectionType.RELAY }]},
  { name: 'Gazeco', models: [{ name: 'Gazeco 18-24', connectionType: ConnectionType.RELAY }]},
  { name: 'Gazlux', models: [
      { name: 'Economy', connectionType: ConnectionType.RELAY },
      { name: 'Standart', connectionType: ConnectionType.RELAY },
      { name: 'Premium', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Geffen', models: [{ name: 'MB 4.1', connectionType: ConnectionType.OPENTHERM }]},
  { name: 'Haier', models: [
      { name: 'Proline TI', connectionType: ConnectionType.RELAY },
      { name: 'Techline TI', connectionType: ConnectionType.RELAY },
      { name: 'Urban', connectionType: ConnectionType.RELAY },
      { name: 'L1PB 12-30', connectionType: ConnectionType.RELAY },
      { name: 'Neoslim', connectionType: ConnectionType.OPENTHERM },
  ]},
  { name: 'Hansa', models: [{ name: 'Inox', connectionType: ConnectionType.OPENTHERM }]},
  { name: 'Heiztechnik', models: [
      { name: 'HT-Tronic', connectionType: ConnectionType.RELAY },
      { name: 'Q PLUS', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Hermann', models: [
      { name: 'Eura', connectionType: ConnectionType.RELAY },
      { name: 'Habitat 2', connectionType: ConnectionType.RELAY },
      { name: 'Thieis', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Hi-Therm', models: [{ name: 'Optimus', connectionType: ConnectionType.RELAY }]},
  { name: 'Hortek', models: [
      { name: 'HR-2K', connectionType: ConnectionType.OPENTHERM },
      { name: 'Q-Series', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Hubert', models: [
      { name: 'ABG 10-35 DY', connectionType: ConnectionType.RELAY },
      { name: 'Smart AGB', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Immergas', models: [
      { name: 'EOLO Mythos', connectionType: ConnectionType.OPENTHERM },
      { name: 'EOLO Star', connectionType: ConnectionType.RELAY },
      { name: 'Nike Mythos', connectionType: ConnectionType.RELAY },
      { name: 'Nike Star', connectionType: ConnectionType.RELAY },
      { name: 'Alpha 24', connectionType: ConnectionType.RELAY },
      { name: 'MINI EOLO', connectionType: ConnectionType.RELAY },
      { name: 'Victrix Zeus Superior', connectionType: ConnectionType.RELAY },
      { name: 'Victrix Tera', connectionType: ConnectionType.RELAY },
      { name: 'Victrix Maior', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'ItalTherm', models: [{ name: 'City Class', connectionType: ConnectionType.OPENTHERM }]},
  { name: 'Jaspi', models: [{ name: 'ECO / LUX', connectionType: ConnectionType.RELAY }]},
  { name: 'Junkers', models: [
      { name: 'Supralin', connectionType: ConnectionType.RELAY },
      { name: 'Cerapur ZBR', connectionType: ConnectionType.RELAY },
      { name: 'Ceraclass Excellence', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Kabola', models: [{ name: 'B-SERIES', connectionType: ConnectionType.RELAY }]},
  { name: 'Kaukora', models: [{ name: 'FIL SPL', connectionType: ConnectionType.RELAY }]},
  { name: 'Kentatsu', models: [
      { name: 'Nobby Balance', connectionType: ConnectionType.RELAY },
      { name: 'Nobby Balance PLUS', connectionType: ConnectionType.RELAY },
      { name: 'Nobby Electro', connectionType: ConnectionType.RELAY },
      { name: 'Nobby Smart', connectionType: ConnectionType.RELAY },
      { name: 'Furst / Kobold', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Kiturami', models: [
      { name: 'Alpha Plus', connectionType: ConnectionType.KITURAMI },
      { name: 'Alpha Plus S', connectionType: ConnectionType.KITURAMI },
      { name: 'Alpha Plus T', connectionType: ConnectionType.KITURAMI },
      { name: 'World Alpha', connectionType: ConnectionType.KITURAMI },
      { name: 'World Alpha S', connectionType: ConnectionType.KITURAMI },
      { name: 'World Alpha C', connectionType: ConnectionType.KITURAMI },
      { name: 'World Alpha CH', connectionType: ConnectionType.KITURAMI },
  ]},
  { name: 'Klover', models: [{ name: 'Style 140-220', connectionType: ConnectionType.RELAY }]},
  { name: 'Koreastar', models: [
      { name: 'ACE', connectionType: ConnectionType.RELAY },
      { name: 'Premium', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Kospel', models: [
      { name: 'ECKO (A, R1, R2, L2M и др.)', connectionType: ConnectionType.RELAY },
      { name: 'EKD.M3', connectionType: ConnectionType.RELAY },
      { name: 'EPCO', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Kotitonttu', models: [{ name: 'Ainova QM', connectionType: ConnectionType.RELAY }]},
  { name: 'LaggarTT', models: [{ name: 'ГАЗ 6000', connectionType: ConnectionType.OPENTHERM }] },
  { name: 'Lamborghini', models: [
      { name: 'ERA, ERA F', connectionType: ConnectionType.OPENTHERM },
      { name: 'Taura D MCA', connectionType: ConnectionType.OPENTHERM },
      { name: 'FL DH', connectionType: ConnectionType.RELAY },
      { name: 'AXE 3', connectionType: ConnectionType.RELAY },
      { name: 'ECO', connectionType: ConnectionType.RELAY },
      { name: 'EXA', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Leberg', models: [
      { name: 'Flamme', connectionType: ConnectionType.RELAY },
      { name: 'RCW-CH', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Лемакс', models: [
      { name: 'Clever (до мая 2023)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Clever (май\'23 - июль\'25)', connectionType: ConnectionType.RELAY },
      { name: 'Clever (с июля 2025)', connectionType: ConnectionType.LEMAX },
      { name: 'Prime V (до мая 2023)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Prime V (май\'23 - июль\'25)', connectionType: ConnectionType.RELAY },
      { name: 'Prime V (с июля 2025)', connectionType: ConnectionType.LEMAX },
      { name: 'Wise (до мая 2023)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Wise (c мая 2023)', connectionType: ConnectionType.RELAY },
      { name: 'Премиум (с горелкой Nova820)', connectionType: ConnectionType.RELAY },
      { name: 'Eco', connectionType: ConnectionType.RELAY },
      { name: 'Proplus', connectionType: ConnectionType.RELAY },
      { name: 'Контроллер RK-2006LP', connectionType: ConnectionType.RELAY },
      { name: 'WESTER WG', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Maktek', models: [{ name: 'LCD', connectionType: ConnectionType.RELAY }]},
  { name: 'Meteor', models: [
      { name: 'C11 - C32', connectionType: ConnectionType.OPENTHERM },
      { name: 'Q3', connectionType: ConnectionType.OPENTHERM },
      { name: 'B20 - B30', connectionType: ConnectionType.OPENTHERM },
      { name: 'M6 - M30', connectionType: ConnectionType.OPENTHERM },
      { name: 'T2', connectionType: ConnectionType.OPENTHERM },
  ]},
  { name: 'Mizudo', models: [
      { name: 'Mizudo (с Opentherm)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Mizudo (без Opentherm)', connectionType: ConnectionType.RELAY }
  ]},
  { name: 'Moguchi', models: [
      { name: 'GBL11F - GBL24F', connectionType: ConnectionType.OPENTHERM },
      { name: 'GBN24F - GBN40F', connectionType: ConnectionType.OPENTHERM },
      { name: 'GBN24HF - GBN40HF', connectionType: ConnectionType.OPENTHERM },
      { name: 'M-EBH4 - M-EBH16', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Monlan', models: [{ name: 'Серия BK', connectionType: ConnectionType.RELAY }]},
  { name: 'Mora-top', models: [
      { name: 'Helios', connectionType: ConnectionType.OPENTHERM },
      { name: 'Electra Comfort', connectionType: ConnectionType.RELAY },
      { name: 'Sirius', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Navien', models: [
      { name: 'NCB700', connectionType: ConnectionType.OPENTHERM },
      { name: 'NGB150 - NGB210', connectionType: ConnectionType.RELAY },
      { name: 'NGB150 - NGB210 (2025г.)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Deluxe', connectionType: ConnectionType.NAVIEN },
      { name: 'Deluxe Plus', connectionType: ConnectionType.NAVIEN },
      { name: 'Deluxe S', connectionType: ConnectionType.NAVIEN },
      { name: 'Deluxe Comfort', connectionType: ConnectionType.NAVIEN },
      { name: 'Deluxe Expert', connectionType: ConnectionType.NAVIEN },
      { name: 'Ace', connectionType: ConnectionType.NAVIEN },
      { name: 'ATMO', connectionType: ConnectionType.NAVIEN },
      { name: 'Deluxe One', connectionType: ConnectionType.RELAY },
      { name: 'EQB', connectionType: ConnectionType.NAVIEN },
      { name: 'GA/GST', connectionType: ConnectionType.RELAY },
      { name: 'GPT/GTD', connectionType: ConnectionType.RELAY },
    ]
  },
  { name: 'Neva (BaltGAZ)', models: [
      { name: 'Turbo / Turbo E', connectionType: ConnectionType.RELAY },
      { name: 'Нева люкс', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Nova Florida', models: [
      { name: 'Aries Dual', connectionType: ConnectionType.RELAY },
      { name: 'Delfis / Delfis Mono', connectionType: ConnectionType.RELAY },
      { name: 'Drago Dual', connectionType: ConnectionType.RELAY },
      { name: 'Libra Dual / Pictor Dual', connectionType: ConnectionType.RELAY },
      { name: 'Nibir', connectionType: ConnectionType.RELAY },
      { name: 'Vela Compact', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Oasis', models: [
      { name: 'BM', connectionType: ConnectionType.RELAY },
      { name: 'RT', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Protherm', models: [
      { name: 'Медведь KLOM17', connectionType: ConnectionType.EBUS },
      { name: 'Медведь KLOM', connectionType: ConnectionType.RELAY },
      { name: 'Медведь KLO / KLZ / PLO / TLO', connectionType: ConnectionType.RELAY },
      { name: 'Рысь (LYNX) HK', connectionType: ConnectionType.RELAY },
      { name: 'Рысь (LYNX) Condens', connectionType: ConnectionType.EBUS },
      { name: 'Пантера v17 (до 2015)', connectionType: ConnectionType.RELAY },
      { name: 'Пантера v18, v19 (с 2015)', connectionType: ConnectionType.EBUS },
      { name: 'Скат, Ray v14 (с 2019)', connectionType: ConnectionType.EBUS },
      { name: 'Скат, Ray v13 (до 2019)', connectionType: ConnectionType.RELAY },
      { name: 'Гепард v18, v19 (с 2015)', connectionType: ConnectionType.EBUS },
      { name: 'Гепард (до 2015)', connectionType: ConnectionType.RELAY },
      { name: 'Дельфин v13 (до 2019)', connectionType: ConnectionType.RELAY },
      { name: 'Дельфин v14 (с 2019)', connectionType: ConnectionType.EBUS },
      { name: 'Ягуар (Jaguar)', connectionType: ConnectionType.RELAY },
      { name: 'Леопард (Leopard)', connectionType: ConnectionType.RELAY },
      { name: 'Тигр (Tiger)', connectionType: ConnectionType.RELAY },
      { name: 'Бизон NL', connectionType: ConnectionType.RELAY },
      { name: 'Гризли (Grizzly)', connectionType: ConnectionType.RELAY },
    ]
  },
  { name: 'Radiant', models: [
      { name: 'RSR', connectionType: ConnectionType.OPENTHERM },
      { name: 'RBS', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Radijator', models: [{ name: 'ECO COMFORT', connectionType: ConnectionType.RELAY }]},
  { name: 'Rendamax', models: [{ name: 'R30', connectionType: ConnectionType.RELAY }]},
  { name: 'Rhoss', models: [{ name: 'THAITY 105', connectionType: ConnectionType.RELAY }]},
  { name: 'Riello', models: [{ name: '5000', connectionType: ConnectionType.RELAY }]},
  { name: 'Rinnai', models: [
      { name: 'BR-K', connectionType: ConnectionType.RINNAI },
      { name: 'BR-U / BR-UE', connectionType: ConnectionType.RINNAI },
      { name: 'BR-S / BR-SE', connectionType: ConnectionType.RINNAI },
      { name: 'BR-R / BR-RE', connectionType: ConnectionType.RINNAI },
      { name: 'BR-RMF', connectionType: ConnectionType.RINNAI },
      { name: 'BR-EMF', connectionType: ConnectionType.RINNAI },
      { name: 'BR-C(LNG)', connectionType: ConnectionType.RINNAI },
  ]},
  { name: 'Roca', models: [
      { name: 'CPA', connectionType: ConnectionType.RELAY },
      { name: 'LIDIA (с панелью CC131)', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Roda', models: [{ name: 'Krafter RMOD / BMOD', connectionType: ConnectionType.RELAY }]},
  { name: 'Rossen', models: [{ name: 'RSA 150-500', connectionType: ConnectionType.RELAY }]},
  { name: 'RoyalTermo', models: [{ name: 'Aquarius', connectionType: ConnectionType.RELAY }]},
  { name: 'Руснит', models: [
      { name: '205N - 209N', connectionType: ConnectionType.RELAY },
      { name: '204M - 209M / 205HM-224HM', connectionType: ConnectionType.RELAY },
      { name: '205K-209K', connectionType: ConnectionType.RELAY },
      { name: '212-270 / 2100', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'РЭКО', models: [
      { name: '4П - 7П', connectionType: ConnectionType.RELAY },
      { name: '3ПМ - 7ПМ', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Saunier Duval', models: [
      { name: 'Isotwin', connectionType: ConnectionType.RELAY },
      { name: 'Thermaclassic', connectionType: ConnectionType.RELAY },
      { name: 'Thermafast', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Savitr', models: [
      { name: 'Control N', connectionType: ConnectionType.RELAY },
      { name: 'MAX / PROF', connectionType: ConnectionType.RELAY },
      { name: 'Monoblock N', connectionType: ConnectionType.RELAY },
      { name: 'Optima / Standart / Premium', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Schuster', models: [{ name: 'SWG', connectionType: ConnectionType.OPENTHERM }]},
  { name: 'Sime', models: [
      { name: '1R / 2R / 2RGT', connectionType: ConnectionType.RELAY },
      { name: 'Bitherm', connectionType: ConnectionType.RELAY },
      { name: 'Brava Slim BFT', connectionType: ConnectionType.RELAY },
      { name: 'Format', connectionType: ConnectionType.RELAY },
      { name: 'GO BF', connectionType: ConnectionType.RELAY },
      { name: 'Metropolis', connectionType: ConnectionType.RELAY },
      { name: 'RMG MK.2', connectionType: ConnectionType.RELAY },
      { name: 'Rondo Estelle', connectionType: ConnectionType.RELAY },
      { name: 'RS MK II', connectionType: ConnectionType.RELAY },
      { name: 'RX / RX TP', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Slant Fin', models: [{ name: 'Galaxy GG / GXH', connectionType: ConnectionType.RELAY }]},
  { name: 'Stanless', models: [{ name: 'ЭВП-48М', connectionType: ConnectionType.RELAY }]},
  { name: 'Stout', models: [
      { name: 'Stout Plus 2022', connectionType: ConnectionType.OPENTHERM },
      { name: 'Stout (до 2022)', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Tahiti', models: [{ name: 'DUAL LINE', connectionType: ConnectionType.RELAY }]},
  { name: 'Теплодар', models: [
      { name: 'Купер ПРО, Купер ПРО Турбо', connectionType: ConnectionType.RELAY },
      { name: 'ПУ Comfort Aqua', connectionType: ConnectionType.RELAY },
      { name: 'ПУ Norma Aqua', connectionType: ConnectionType.RELAY },
      { name: 'ПУВН10 (новый, с реле термостата)', connectionType: ConnectionType.RELAY },
      { name: 'ПУВН10 (старый, без реле термостата)', connectionType: ConnectionType.CONTACTOR },
      { name: 'ЭПВ-12(15,18)', connectionType: ConnectionType.CONTACTOR },
  ]},
  { name: 'Termodinamik', models: [{ name: 'EKY S', connectionType: ConnectionType.RELAY }]},
  { name: 'Termal', models: [{ name: 'Эл. камины 6-20кВт', connectionType: ConnectionType.RELAY }]},
  { name: 'Termet', models: [{ name: 'Miniterm / Maxiterm', connectionType: ConnectionType.OPENTHERM }]},
  { name: 'Termica', models: [
      { name: 'Electrica', connectionType: ConnectionType.RELAY },
      { name: 'Grata', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'TermoBalt', models: [{ name: 'Эл.котлы 3-30 кВт', connectionType: ConnectionType.RELAY }]},
  { name: 'Teplodom', models: [{ name: 'I-TRM', connectionType: ConnectionType.RELAY }]},
  { name: 'Thermex', models: [
      { name: 'Vega', connectionType: ConnectionType.OPENTHERM },
      { name: 'Xantus', connectionType: ConnectionType.OPENTHERM },
      { name: 'Andromeda', connectionType: ConnectionType.RELAY },
      { name: 'SKIF', connectionType: ConnectionType.RELAY },
      { name: 'Boss', connectionType: ConnectionType.RELAY },
      { name: 'Hydra', connectionType: ConnectionType.RELAY },
      { name: 'Quantum', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Thermo Trust', models: [
      { name: 'ST / STI', connectionType: ConnectionType.RELAY },
      { name: 'Star Monoblock', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Thermona', models: [
      { name: 'EL 8-45', connectionType: ConnectionType.OPENTHERM },
      { name: 'Therm Duo', connectionType: ConnectionType.OPENTHERM },
      { name: 'Therm Trio', connectionType: ConnectionType.OPENTHERM },
      { name: 'Therm (LXZ.A / TLXZ.A / TLXZE.A)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Therm (TCX.A / CX.A)', connectionType: ConnectionType.RELAY },
      { name: 'Therm (L / LN / CLN / TCLN)', connectionType: ConnectionType.RELAY },
      { name: 'Therm (TCL / TLC )', connectionType: ConnectionType.RELAY },
      { name: 'Therm (LX / LXC / CX)', connectionType: ConnectionType.RELAY },
      { name: 'Therm (E-B / P-B / EZ-B)', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Thision', models: [{ name: 'L ECO', connectionType: ConnectionType.OPENTHERM }]},
  { name: 'Tiberis', models: [
      { name: 'Cube F', connectionType: ConnectionType.RELAY },
      { name: 'Mini / Mini S', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Титан', models: [{ name: 'Z30E-Z95E', connectionType: ConnectionType.RELAY }]},
  { name: 'TIS', models: [
      { name: 'Tronic 83', connectionType: ConnectionType.RELAY },
      { name: 'Tronic 260', connectionType: ConnectionType.RELAY },
      { name: 'Tronic 496P', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Titan', models: [{ name: 'Titan Z 30E-95E', connectionType: ConnectionType.RELAY }]},
  { name: 'Unical', models: [
      { name: '!DEA', connectionType: ConnectionType.RELAY },
      { name: '!VEN', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Vaillant', models: [
      { name: 'atmoTEC Pro VU/VUW', connectionType: ConnectionType.EBUS },
      { name: 'atmoTEC Plus VU/VUW', connectionType: ConnectionType.EBUS },
      { name: 'turboTEC Pro VU/VUW', connectionType: ConnectionType.EBUS },
      { name: 'turboTEC Plus VU/VUW', connectionType: ConnectionType.EBUS },
      { name: 'turboFIT VUW', connectionType: ConnectionType.RELAY },
      { name: 'eloBLOCK VE.../14', connectionType: ConnectionType.EBUS },
      { name: 'eloBLOCK VE.../13', connectionType: ConnectionType.RELAY },
      { name: 'atmoCRAFT', connectionType: ConnectionType.RELAY },
      { name: 'atmoMAX PRO', connectionType: ConnectionType.RELAY },
      { name: 'atmoVIT', connectionType: ConnectionType.RELAY },
      { name: 'ecoTEC', connectionType: ConnectionType.EBUS },
      { name: 'ecoVIT', connectionType: ConnectionType.EBUS },
      { name: 'ecoCRAFT exclusiv', connectionType: ConnectionType.EBUS },
      { name: 'ecoCOMPACT', connectionType: ConnectionType.EBUS },
      { name: 'turboMAX', connectionType: ConnectionType.RELAY },
    ]
  },
  { name: 'Vieir', models: [{ name: 'Vieir 5-13', connectionType: ConnectionType.RELAY }]},
  { name: 'Viessmann', models: [
      { name: 'Vitogas 100-F', connectionType: ConnectionType.RELAY },
      { name: 'Vitopend 100-W 2019 (A1HB/A1JB)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Vitopend 111-W (WHSB)', connectionType: ConnectionType.RELAY },
      { name: 'Vitopend 222-W (WHSA)', connectionType: ConnectionType.RELAY },
      { name: 'Vitodens 050-W (BPJC/B0KA/B0HA/BPKA)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Vitodens 100-W (WB1B/WB1C/B1HC/B1KC)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Vitodens 111-W (B1LD)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Vitodens 222-F', connectionType: ConnectionType.RELAY },
      { name: 'EKCO.T (Kospel)', connectionType: ConnectionType.RELAY },
      { name: 'Vitotron 100 (VMN3)', connectionType: ConnectionType.RELAY },
      { name: 'Vitotronic 050/100/200', connectionType: ConnectionType.RELAY },
    ]
  },
  { name: 'Vulcan', models: [{ name: 'Контроллер DM320', connectionType: ConnectionType.RELAY }]},
  { name: 'WALLCON', models: [{ name: 'X-Treme', connectionType: ConnectionType.RELAY }]},
  { name: 'WARM', models: [{ name: 'Auros', connectionType: ConnectionType.OPENTHERM }]},
  { name: 'Wattek', models: [{ name: 'Eltek', connectionType: ConnectionType.RELAY }]},
  { name: 'Wert (WertRus)', models: [
      { name: 'Eco', connectionType: ConnectionType.RELAY },
      { name: 'Nova', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Wespe Heizung', models: [
      { name: 'Complete U', connectionType: ConnectionType.RELAY },
      { name: 'Industrial', connectionType: ConnectionType.RELAY },
      { name: 'Elite WH L', connectionType: ConnectionType.RELAY },
      { name: 'Foreman', connectionType: ConnectionType.RELAY },
      { name: 'Kombi', connectionType: ConnectionType.RELAY },
      { name: 'Master', connectionType: ConnectionType.RELAY },
      { name: 'MF', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Wolf', models: [
      { name: 'FGB / FGB-K', connectionType: ConnectionType.EBUS },
      { name: 'FGG / FGG-K', connectionType: ConnectionType.OPENTHERM },
      { name: 'CGG-3 / CGG-3K', connectionType: ConnectionType.EBUS },
      { name: 'CGB / CGB-2', connectionType: ConnectionType.EBUS },
      { name: 'CGW-2 / CGS-2', connectionType: ConnectionType.EBUS },
      { name: 'MGK-2', connectionType: ConnectionType.EBUS },
      { name: 'CGG-1K / CGG-2K', connectionType: ConnectionType.EBUS },
      { name: 'TGB', connectionType: ConnectionType.RELAY },
      { name: 'MKS / CHK / CHU', connectionType: ConnectionType.RELAY },
      { name: 'Контроллер R16 Digi compact', connectionType: ConnectionType.EBUS },
      { name: 'Контроллер R31/32', connectionType: ConnectionType.RELAY },
  ]},
  { name: 'Zota', models: [
      { name: 'Solid / Solid-X', connectionType: ConnectionType.OPENTHERM },
      { name: 'LUX-X', connectionType: ConnectionType.OPENTHERM },
      { name: 'MK-X / MK-X PLUS', connectionType: ConnectionType.OPENTHERM },
      { name: 'MK-S', connectionType: ConnectionType.RELAY },
      { name: 'MK-S PLUS', connectionType: ConnectionType.OPENTHERM },
      { name: 'Balance', connectionType: ConnectionType.RELAY },
      { name: 'Solo', connectionType: ConnectionType.RELAY },
      { name: 'Lux', connectionType: ConnectionType.RELAY },
      { name: 'ПУ ЭВТ-SSR, ПУ ЭВТ И1', connectionType: ConnectionType.RELAY },
      { name: 'ПУ ЭВТ Серия "PROM" (2024)', connectionType: ConnectionType.OPENTHERM },
      { name: 'ПУ ЭВТ Серия "PROM" (до 2024)', connectionType: ConnectionType.RELAY },
      { name: 'Pellet', connectionType: ConnectionType.RELAY },
      { name: 'Reserve SET', connectionType: ConnectionType.RELAY },
      { name: 'Smart SE', connectionType: ConnectionType.RELAY },
      { name: 'Stahanov', connectionType: ConnectionType.RELAY },
      { name: 'ecoMAX350P2-Z', connectionType: ConnectionType.RELAY },
    ]
  },
  { name: 'Эван', models: [
      { name: 'Expert PLUS', connectionType: ConnectionType.OPENTHERM },
      { name: 'Warmos / Warmos IV', connectionType: ConnectionType.RELAY },
      { name: 'Next', connectionType: ConnectionType.RELAY },
      { name: 'Next PLUS', connectionType: ConnectionType.OPENTHERM },
      { name: 'Practic', connectionType: ConnectionType.RELAY },
      { name: 'Practic (New 2022)', connectionType: ConnectionType.OPENTHERM },
      { name: 'Forward', connectionType: ConnectionType.OPENTHERM },
      { name: 'C-1 / C-2', connectionType: ConnectionType.RELAY },
      { name: 'ЭПО', connectionType: ConnectionType.RELAY },
      { name: 'Novator', connectionType: ConnectionType.RELAY },
      { name: 'Expert', connectionType: ConnectionType.RELAY },
    ]
  },
];

const sortedBrands = [...RAW_BRANDS].sort((a, b) => {
  const isCyrillicA = /[А-Яа-я]/.test(a.name[0]);
  const isCyrillicB = /[А-Яа-я]/.test(b.name[0]);
  if (isCyrillicA && !isCyrillicB) return 1;
  if (!isCyrillicA && isCyrillicB) return -1;
  return a.name.localeCompare(b.name, 'ru');
});

const priorityBrandsList = PRIORITY_BRANDS.map(name => sortedBrands.find(b => b.name === name)).filter(Boolean) as import('./types').BoilerBrand[];
priorityBrandsList.sort((a, b) => {
  const isCyrillicA = /[А-Яа-я]/.test(a.name[0]);
  const isCyrillicB = /[А-Яа-я]/.test(b.name[0]);
  if (isCyrillicA && !isCyrillicB) return 1;
  if (!isCyrillicA && isCyrillicB) return -1;
  return a.name.localeCompare(b.name, 'ru');
});

export const BOILER_BRANDS: import('./types').BoilerBrand[] = [
  ...priorityBrandsList,
  { name: '------------------------------', models: [] },
  ...sortedBrands
];

export const OPTIONAL_ITEMS = ['ec01011'];

export const PRODUCTS: Product[] = [
  { id: 'ec01v40', name: 'Центральный блок управления ectoControl v.4.0', price: 18900, category: 'base', image: '/download/images_resized/ec01v40.jpg', dinModules: 12, cartId: '54' },
  { id: 'ec01105', name: 'Блок управления ectoControl Start v.1.0', price: 15900, category: 'base', image: '/download/images_resized/ec01105.jpg', cartId: '159' },
  { id: 'ec01001', name: 'Датчик температуры воздуха проводной', price: 1390, category: 'sensor', consumesPort: { type: 'TC', amount: 1 }, image: '/download/images_resized/ec01001.jpg', cartId: '63' },
  { id: 'ec01002', name: 'Датчик температуры воздуха проводной, RS485', price: 3190, category: 'sensor', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01002.jpg', cartId: '66' },
  { id: 'ec01003', name: 'Датчик температуры проводной в гильзе', price: 1590, category: 'sensor', consumesPort: { type: 'TC', amount: 1 }, image: '/download/images_resized/ec01003.jpg', cartId: '65' },
  { id: 'ec01004', name: 'Датчик температуры проводной в гильзе, RS485', price: 3390, category: 'sensor', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01004.jpg', cartId: '64' },
  { id: 'ec01005', name: 'Беспроводной датчик температуры воздуха', price: 3490, category: 'sensor', consumesPort: { type: 'RADIO', amount: 1 }, image: '/download/images_resized/ec01005.jpg', cartId: '67' },
  { id: 'ec01041', name: 'Беспроводной датчик температуры, LoRa', price: 4590, category: 'sensor', consumesPort: { type: 'LORA', amount: 1 }, image: '/download/images_resized/ec01041.jpg', cartId: '68' },
  { id: 'ec01064', name: 'Беспроводной датчик температуры с гильзой, LoRa', price: 4990, category: 'sensor', consumesPort: { type: 'LORA', amount: 1 }, image: '/download/images_resized/ec01064.jpg', cartId: '135' },
  { id: 'ec01042', name: 'Адаптер OpenTherm, RS485', price: 3590, category: 'adapter', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01042.jpg', dinModules: 2.2, cartId: '95' },
  { id: 'ec01057', name: 'Адаптер OpenTherm, DIN, RS485', price: 3590, category: 'adapter', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01057.jpg', dinModules: 2.2, cartId: '166' },
  { id: 'ec01045', name: 'Адаптер E-Bus, RS485', price: 3590, category: 'adapter', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01045.jpg', dinModules: 2.2, cartId: '96' },
  { id: 'ec01058', name: 'Адаптер Navien, RS485', price: 3590, category: 'adapter', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01058.jpg', dinModules: 2.2, cartId: '94' },
  { id: 'ec01095', name: 'Адаптер BSB, RS485', price: 3590, category: 'adapter', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01095.jpg', dinModules: 2.2, cartId: '155' },
  { id: 'ec01093', name: 'Адаптер Arderia, RS485', price: 3590, category: 'adapter', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01093.jpg', dinModules: 2.2, cartId: '147' },
  { id: 'ec01094', name: 'Адаптер Rinnai, RS485', price: 3590, category: 'adapter', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01094.jpg', dinModules: 2.2, cartId: '156' },
  { id: 'ec01092', name: 'Адаптер Lemax, RS485', price: 3590, category: 'adapter', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01092.jpg', dinModules: 2.2, cartId: '148' },
  { id: 'ec01108', name: 'Адаптер Kiturami, RS485', price: 3590, category: 'adapter', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01108.jpg', dinModules: 2.2, cartId: '161' },
  { id: 'ec01125', name: 'Адаптер EMS+, RS485', price: 3590, category: 'adapter', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01125.jpg', dinModules: 2.2, cartId: '168' },
  { id: 'ec01097', name: 'Адаптер ШИМ, RS485', price: 5590, category: 'adapter', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01097.jpg', dinModules: 2.2, cartId: '154' },
  { id: 'ec01098', name: 'Адаптер 0-10В, RS485', price: 5590, category: 'adapter', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01098.jpg', dinModules: 2.2, cartId: '69' },
  { id: 'ec01025', name: 'Блок расширения на 10 реле проводной, RS485', price: 11490, category: 'expansion', consumesPort: { type: 'DOP', amount: 1 }, providesPort: [{ type: 'RELAY', amount: 10 }], image: '/download/images_resized/ec01025.jpg', dinModules: 9, cartId: '77' },
  { id: 'ec01033', name: 'Разветвитель датчиков/устройств, RS485', price: 700, category: 'expansion', consumesPort: { type: 'DOP', amount: 1 }, providesPort: [{ type: 'DOP', amount: 8 }], image: '/download/images_resized/ec01033.jpg', cartId: '71' },
  { id: 'ec01107', name: 'Разветвитель датчиков/устройств, DIN, RS485 (Modbus)', price: 1290, category: 'expansion', consumesPort: { type: 'DOP', amount: 1 }, providesPort: [{ type: 'DOP', amount: 8 }], image: '/download/images_resized/ec01107.jpg', cartId: '158' },
  { id: 'ec01060', name: 'Блок управления смесительными контурами, RS485', price: 15990, category: 'expansion', consumesPort: { type: 'DOP', amount: 1 }, providesPort: [{ type: 'MIXER', amount: 4 }, { type: 'TS', amount: 4 }], image: '/download/images_resized/ec01060.jpg', dinModules: 9, cartId: '118' },
  { id: 'ec01101', name: 'Блок смесительный пропорциональный 0-10В RS485', price: 16990, category: 'expansion', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01101.jpg', dinModules: 9, cartId: '150' },
  { id: 'ec01055', name: 'Разветвитель адресный для контактных датчиков, RS485', price: 1990, category: 'expansion', consumesPort: { type: 'DOP', amount: 1 }, providesPort: [{ type: 'CONTACT', amount: 8 }], image: '/download/images_resized/ec01055.jpg', cartId: '73' },
  { id: 'ec01096', name: 'Адаптер для беспроводных датчиков LoRa, DIN', price: 2490, category: 'expansion', consumesPort: { type: 'DOP', amount: 1 }, providesPort: [{ type: 'LORA', amount: 32 }], image: '/download/images_resized/ec01096.jpg', dinModules: 2.2, cartId: '149' },
  { id: 'ec01090', name: 'Блок измерительный на 8 каналов, RS485', price: 16990, category: 'expansion', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01090.jpg', dinModules: 9, cartId: '146' },
  { id: 'ec01099', name: 'Сервопривод ectoControl нормально-закрытый, 230В', price: 2690, category: 'other', image: '/download/images_resized/ec01099.jpg', cartId: '151' },
  { id: 'ec01065', name: 'Шаровой кран 1/2", 12В, Neptun Click SE Bugatti с электроприводом', price: 14000, category: 'other', consumesPort: { type: 'RELAY', amount: 1 }, image: '/download/images_resized/ec01065.jpg', cartId: '127' },
  { id: 'ec01066', name: 'Шаровой кран 3/4", 12В, Neptun Click SE Bugatti с электроприводом', price: 14500, category: 'other', consumesPort: { type: 'RELAY', amount: 1 }, image: '/download/images_resized/ec01066.jpg', cartId: '130' },
  { id: 'ec01067', name: 'Шаровой кран 1", 12В, Neptun Click SE Bugatti с электроприводом', price: 17500, category: 'other', consumesPort: { type: 'RELAY', amount: 1 }, image: '/download/images_resized/ec01067.jpg', cartId: '131' },
  { id: 'ec01079', name: 'Беспроводное реле 10А, LoRa', price: 4590, category: 'other', consumesPort: { type: 'LORA', amount: 1 }, image: '/download/images_resized/ec01079.jpg', cartId: '145' },
  { id: 'ec01009', name: 'Беспроводной электропривод для перекрытия воды/газа', price: 3590, category: 'other', consumesPort: { type: 'RADIO', amount: 1 }, image: '/download/images_resized/ec01009.jpg', cartId: '80' },
  { id: 'ec01011', name: 'Провод для подключения котла', price: 290, category: 'other', image: '/download/images_resized/ec01011.jpg', cartId: '91' },
  { id: 'ec01091', name: 'Термостат, комнатный регулятор проводной RS485', price: 6990, category: 'sensor', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01091.jpg', cartId: '157' },
  { id: 'ec01080', name: 'Термостат, комнатный регулятор беспроводной, LoRa', price: 6990, category: 'sensor', consumesPort: { type: 'LORA', amount: 1 }, image: '/download/images_resized/ec01080.jpg', cartId: '140' },
  { id: 'ec01010', name: 'Датчик давления (манометр) проводной', price: 3590, category: 'sensor', consumesPort: { type: 'CONTACT', amount: 2 }, image: '/download/images_resized/ec01010.jpg', cartId: '81' },
  { id: 'ec01008', name: 'Датчик утечки природного газа проводной', price: 2990, category: 'sensor', consumesPort: { type: 'CONTACT', amount: 1 }, image: '/download/images_resized/ec01008.jpg', cartId: '87' },
  { id: 'ec01068', name: 'Беспроводной извещатель угарного газа CO', price: 3990, category: 'sensor', consumesPort: { type: 'RADIO', amount: 1 }, image: '/download/images_resized/ec01068.jpg', cartId: '134' },
  { id: 'ec01015', name: 'Датчик дыма проводной', price: 1490, category: 'sensor', consumesPort: { type: 'CONTACT', amount: 1 }, image: '/download/images_resized/ec01015.jpg', cartId: '105' },
  { id: 'ec01017', name: 'Беспроводной датчик дыма', price: 3690, category: 'sensor', consumesPort: { type: 'RADIO', amount: 1 }, image: '/download/images_resized/ec01017.jpg', cartId: '74' },
  { id: 'ec01006', name: 'Датчик протечки воды проводной', price: 1490, category: 'sensor', consumesPort: { type: 'CONTACT', amount: 1 }, image: '/download/images_resized/ec01006.jpg', cartId: '78' },
  { id: 'ec01007', name: 'Беспроводной датчик протечки воды', price: 3690, category: 'sensor', consumesPort: { type: 'RADIO', amount: 1 }, image: '/download/images_resized/ec01007.jpg', cartId: '79' },
  { id: 'ec01056', name: 'Беспроводной датчик протечки воды LoRa', price: 4490, category: 'sensor', consumesPort: { type: 'LORA', amount: 1 }, image: '/download/images_resized/ec01056.jpg', cartId: '117' },
  { id: 'ec01013', name: 'Датчик движения проводной', price: 1490, category: 'sensor', consumesPort: { type: 'CONTACT', amount: 1 }, image: '/download/images_resized/ec01013.jpg', cartId: '62' },
  { id: 'ec01014', name: 'Беспроводной датчик движения', price: 3690, category: 'sensor', consumesPort: { type: 'RADIO', amount: 1 }, image: '/download/images_resized/ec01014.jpg', cartId: '50' },
  { id: 'ec01012', name: 'Датчик открытия двери/окна проводной', price: 590, category: 'sensor', consumesPort: { type: 'CONTACT', amount: 1 }, image: '/download/images_resized/ec01012.jpg', cartId: '85' },
  { id: 'ec01043', name: 'Беспроводной датчик открытия двери/окна', price: 2990, category: 'sensor', consumesPort: { type: 'RADIO', amount: 1 }, image: '/download/images_resized/ec01043.jpg', cartId: '84' },
  { id: 'ec01016', name: 'Свето-звуковой оповещатель проводной', price: 1190, category: 'other', consumesPort: { type: '123', amount: 1 }, image: '/download/images_resized/ec01016.jpg', cartId: '82' },
  { id: 'ec01016-1', name: 'Свето-звуковой оповещатель комбинированный', price: 1790, category: 'other', consumesPort: { type: '123', amount: 1 }, image: '/download/images_resized/ec01016-1.jpg', cartId: '83' },
  { id: 'ec01018', name: 'Микрофон проводной', price: 950, category: 'other', consumesPort: { type: 'JACK', amount: 1 }, image: '/download/images_resized/ec01018.jpg', cartId: '88' },
  { id: 'ec01019', name: 'Беспроводной брелок режима охраны', price: 2190, category: 'other', consumesPort: { type: 'RADIO', amount: 1 }, image: '/download/images_resized/ec01019.jpg', cartId: '86' },
  { id: 'ec01020', name: 'Ключ Touch Memory (считыватель и 3 ключа)', price: 990, category: 'other', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01020.jpg', cartId: '101' },
  { id: 'ec01061', name: 'Промежуточное реле Shenler', price: 1880, category: 'other', consumesPort: { type: 'RELAY', amount: 0 }, image: '/download/images_resized/ec01061.jpg', cartId: '125' },
  { id: 'ec01021', name: 'Блок управления 2-мя розетками, RS485', price: 3290, category: 'expansion', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01021.jpg', cartId: '76' },
  { id: 'ec01022', name: 'Беспроводная розетка 16А', price: 3590, category: 'other', consumesPort: { type: 'RADIO', amount: 1 }, image: '/download/images_resized/ec01022.jpg', cartId: '75' },
  { id: 'ec01023', name: 'Контактор для перем. тока, 4кВт (18А)', price: 990, category: 'other', consumesPort: { type: 'RELAY', amount: 1 }, image: '/download/images_resized/ec01023.jpg', dinModules: 2.6, cartId: '99' },
  { id: 'ec01024', name: 'Контактор для перем. Тока, 7кВт (32А)', price: 1790, category: 'other', consumesPort: { type: 'RELAY', amount: 1 }, image: '/download/images_resized/ec01024.jpg', dinModules: 2.6, cartId: '100' },
  { id: 'ec01074', name: 'Счетчик электроэнергии 1-фазный CHINT', price: 4290, category: 'other', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01074.jpg', dinModules: 2.2, cartId: '102' },
  { id: 'ec01075', name: 'Счетчик электроэнергии 3-фазный CHINT', price: 7490, category: 'other', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01075.jpg', dinModules: 4, cartId: '103' },
  { id: 'ec01026', name: 'Датчик наличия сети 220В проводной', price: 1390, category: 'sensor', consumesPort: { type: 'CONTACT', amount: 1 }, image: '/download/images_resized/ec01026.jpg', cartId: '89' },
  { id: 'ec01027', name: 'Выносная GSM антенна проводная', price: 390, category: 'other', consumesPort: { type: 'SMA', amount: 1 }, image: '/download/images_resized/ec01027.jpg', cartId: '107' },
  { id: 'ec01028', name: 'Усиленный аккумулятор, 12В, 7 Ач', price: 1990, category: 'other', image: '/download/images_resized/ec01028.jpg', cartId: '92' },
  { id: 'ec01029', name: 'Датчик уровня жидкости проводной', price: 1590, category: 'sensor', consumesPort: { type: 'CONTACT', amount: 1 }, image: '/download/images_resized/ec01029.jpg', cartId: '90' },
  { id: 'ec01030', name: 'Датчик влажности воздуха проводной, RS485', price: 3190, category: 'sensor', consumesPort: { type: 'DOP', amount: 1 }, image: '/download/images_resized/ec01030.jpg', cartId: '70' },
  { id: 'ec01054', name: 'Датчик влажности воздуха беспроводной', price: 3290, category: 'sensor', consumesPort: { type: 'RADIO', amount: 1 }, image: '/download/images_resized/ec01054.jpg', cartId: '97' },
  { id: 'ec01062', name: 'Коннектор 4P4C (RJ11), 10шт', price: 50, category: 'other', image: '/download/images_resized/ec01062.jpg', cartId: '108' },
  { id: 'ec01031', name: 'Батарейка (запасная) для датчиков', price: 290, category: 'other', image: '/download/images_resized/ec01031.jpg', cartId: '93' },
  { id: 'ec01063', name: 'Сетевой адаптер MeanWell 14В 1.5А DIN', price: 2500, category: 'other', image: '/download/images_resized/ec01063.jpg', dinModules: 2.2, cartId: '133' },
  { id: 'ec01039', name: 'Адаптер питания 14В, 2А', price: 950, category: 'other', image: '/download/images_resized/ec01039.jpg', cartId: '104' },
  { id: 'ec01114', name: 'Датчик температуры NTC 10K', price: 990, category: 'sensor', image: '/download/images_resized/ec01114.jpg', cartId: '162' },
  { id: 'ec01124', name: 'Провод для котла с клеммником Baxi, 2м', price: 150, category: 'other', image: '/download/images_resized/ec01124.jpg', cartId: '167' },
];